# Generated by Django 4.2.4 on 2023-09-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bikeLists", "0003_remove_bikelist_company_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikelist",
            name="company_details",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bikelist",
                to="bikeLists.companydetails",
            ),
            preserve_default=False,
        ),
    ]
