# Generated by Django 4.2.4 on 2023-09-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bikeLists", "0006_review_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikelist",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="bikelist",
            name="number_of_rating",
            field=models.IntegerField(default=0),
        ),
    ]
