# Generated by Django 4.2.4 on 2023-11-15 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bikeLists", "0007_bikelist_avg_rating_bikelist_number_of_rating"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BikeList",
            new_name="Bike",
        ),
    ]
